### ISSUE TITLE
index `chick`s

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/uqbar-core#198]
see discussion web+urbitgraph://group/~hocwyn-tipwex/uqbar-event-horizon-forever/graph/~hocwyn-tipwex/help-5287/170141184505877285217227401785384108032

**Comment by tadad** [comment]
Similar to how etherscan.io let's you see the state changes for each transaction (see [here](https://etherscan.io/tx/0xe96df22d63207ae402aa796bf4c01b5efba5e206146828ba3589cb0de22ba7aa#statechange)) we could index the `chick` results so that people can see what grains were issued/burned/modified, and exactly how the state changed

**Comment by dr-frmr** [comment]
we got this now
