### ISSUE TITLE
indexer: /newest/item/ scry broken?

### ISSUE THREAD

**Issue by bacwyls** [uqbar-dao/uqbar-core#294]
`.^(update:ui %gx /=uqbar=/indexer/item/0x0/0x3d7a.7477.a55d.721c.3db4.bdc3.b675.96ed.8b3e.0b23.7c0e.6a11.121a.e488.2eee.08c6/noun)`
this returns a **non-null** history of the item.

`.^(update:ui %gx /=uqbar=/indexer/newest/item/0x0/0x3d7a.7477.a55d.721c.3db4.bdc3.b675.96ed.8b3e.0b23.7c0e.6a11.121a.e488.2eee.08c6/noun)`
this returns ~

**Comment by hosted-fornet** [comment]
Thanks for the report. I believe this is the same issue we are working to solve in PR #295. Until that change is merged and deployed, please try

```hoon

```

**Comment by hosted-fornet** [comment]
To expand a bit, we believe the problem is that your local %indexer can sometimes get batches that have some fields bunted, and that the source of those batches are those `+on-watch`  arms being changed in that PR. The command above will grab the canonical, correct batches from ~bacdun's %indexer, which should make the `/newest` scries work properly.

**Comment by bacwyls** [comment]
that worked, thanks!

**Comment by hosted-fornet** [comment]
To follow up, the fix in PR #295 has been merged and deployed, so you shouldn't see this problem again.
